### ISSUE TITLE
SAMAnalytical.Add space error

### ISSUE THREAD

**Issue by michaldengusiak** [HoareLea/SAM#112]
**Describe the bug**

we can not run with space or space and panels

**Screenshots**

![image](https://user-images.githubusercontent.com/26113670/84512352-c1e59100-acbf-11ea-89f0-4c9c40867760.png)
![image](https://user-images.githubusercontent.com/26113670/84512423-e0e42300-acbf-11ea-8cf0-55d91ae56baf.png)

**Test file**

[bugAddSpace.zip](https://github.com/HoareLea/SAM/files/4771332/bugAddSpace.zip)

**Comment by ZiolkowskiJakub** [comment]
Fixed here https://github.com/HoareLea/SAM/commit/2e6fe9f98ba1d38b6a6265ffd585fa5b7bbf4fa6

![image](https://user-images.githubusercontent.com/16777757/84560105-9357cc80-ad38-11ea-900a-dbf1b6b0808f.png)

**Comment by michaldengusiak** [comment]
fixed and approved
![image](https://user-images.githubusercontent.com/26113670/84560965-8d65e980-ad40-11ea-961c-1b01fc0dd86c.png)
