### ISSUE TITLE
add CoplanarPanels for AjdCluster

### ISSUE THREAD

**Issue by michaldengusiak** [HoareLea/SAM#121]
**Describe the solution you'd like**

SAMAnalytical.MergeCoplanarPanels work on AdjCluster

**Additional context**

![image](https://user-images.githubusercontent.com/26113670/84863665-32e4ca00-b06d-11ea-9927-4d8d523e120e.png)

**Comment by ZiolkowskiJakub** [comment]
MergeCoplanarPanels has been modified to work on AdjacencyCluster, Panel and AnalytycalModel input

**Comment by michaldengusiak** [comment]
merge  needs improvements
![image](https://user-images.githubusercontent.com/26113670/87526699-14311d80-c683-11ea-8848-7d7bb2b60412.png)

**Comment by michaldengusiak** [comment]
fixed and approved

![image](https://user-images.githubusercontent.com/26113670/87527010-6d994c80-c683-11ea-8354-a828829f78d5.png)
