### ISSUE TITLE
add SAMAnalytical.AddAperture for AjdCluster

### ISSUE THREAD

**Issue by michaldengusiak** [HoareLea/SAM#122]
**Describe the solution you'd like**

allow SAMAnalytical.AddAperture to take AdjCluster
**Additional context**

**Comment by ZiolkowskiJakub** [comment]
SAMAnalytical.AddAperture Updated to accommodate AdjacencyCluster and AnalyticalModel input

**Comment by michaldengusiak** [comment]
it works now on three inputs: Panels, AdjClustert, AnalyticalModel
tested and approved

![image](https://user-images.githubusercontent.com/26113670/85379065-3bd51000-b533-11ea-839b-16b319b248e2.png)
