### ISSUE TITLE
floor type

### ISSUE THREAD

**Issue by michaldengusiak** [HoareLea/SAM#124]
**Describe the bug**

when generating the default floor... GRD is used even if the exposed floor is used

**Steps to recreate the bug**

Versions: Revit , Rhino

**Screenshots**

![image](https://user-images.githubusercontent.com/26113670/85143982-66c51880-b242-11ea-9529-e3d58eb522dc.png)

**Test file**

any file  when generating from lines and min elevation >0, ie gbXML_Test6a

**Comment by ZiolkowskiJakub** [comment]
Fixed. New Inpout added to Component - Elevation_Ground (default value equals to 0):
![image](https://user-images.githubusercontent.com/16777757/87416530-bdfea480-c5c6-11ea-833b-cf7d63136d9a.png)

**Comment by michaldengusiak** [comment]
testd and APPROVED
![image](https://user-images.githubusercontent.com/26113670/87522880-16dd4400-c67e-11ea-970a-8c7ef243925b.png)
