### ISSUE TITLE
Update Name and Location of Space 

### ISSUE THREAD

**Issue by ZiolkowskiJakub** [HoareLea/SAM#126]
**Describe the solution you'd like**
Create new Grasshopper Component to update Name and Location of Space

**Additional context**
N/A

**Comment by ZiolkowskiJakub** [comment]
New node created:
![image](https://user-images.githubusercontent.com/16777757/85297751-0f6db500-b49b-11ea-9e17-6bbe4894e7b6.png)

**Comment by michaldengusiak** [comment]
it works fine but adds new instance rather than update existing space
![image](https://user-images.githubusercontent.com/26113670/85300982-2ca48280-b49f-11ea-8def-49d49c31b682.png)
![image](https://user-images.githubusercontent.com/26113670/85301012-35955400-b49f-11ea-9d7a-45421aa9a349.png)

**Comment by ZiolkowskiJakub** [comment]
Issue Fixed. Please check again.

**Comment by michaldengusiak** [comment]
tested and approved
