### ISSUE TITLE
bug protection from unplaced Spaces

### ISSUE THREAD

**Issue by michaldengusiak** [HoareLea/SAM#134]
**Describe the bug**

filter out unplaced spaces

**Steps to recreate the bug**

Versions: Revit , Rhino

**Screenshots**

![image](https://user-images.githubusercontent.com/26113670/86365221-210c4500-bc71-11ea-83eb-821a6f7ef53a.png)

**Test file**

**Comment by ZiolkowskiJakub** [comment]
Fixed. You can use IsPlaced Property to filter unplaced spaces:
![image](https://user-images.githubusercontent.com/16777757/87414932-5f382b80-c5c4-11ea-8841-ef00ccc4de20.png)

**Comment by michaldengusiak** [comment]
ok works fine but we need to implement greater than

![image](https://user-images.githubusercontent.com/26113670/87517276-8b13e980-c676-11ea-9ec1-68e9bce5154a.png)
