### ISSUE TITLE
display 2D points

### ISSUE THREAD

**Issue by michaldengusiak** [HoareLea/SAM#142]
**Describe the bug**

**Steps to recreate the bug**

Versions: Revit , Rhino

**Screenshots**

![image](https://user-images.githubusercontent.com/26113670/87022088-e43ed180-c1cd-11ea-9a61-f34850cf7ae9.png)

**Test file**

[bugPoint2D.zip](https://github.com/HoareLea/SAM/files/4895765/bugPoint2D.zip)

**Comment by ZiolkowskiJakub** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/16777757/87411895-4594e500-c5c0-11ea-894a-25008f08431a.png)

**Comment by michaldengusiak** [comment]
tested and approved

![Uploading image.png…]()
