### ISSUE TITLE
Add AdjacentSpaceNames to AdjacencyCluster

### ISSUE THREAD

**Issue by ZiolkowskiJakub** [HoareLea/SAM#145]
**Describe the solution you'd like**
Add AdjacentSpaceNames (text) to AdjacencyCluster

**Comment by ZiolkowskiJakub** [comment]
New Component Added:

![image](https://user-images.githubusercontent.com/16777757/87446735-996bf200-c5f1-11ea-9051-502041479f13.png)

Works for AdjacencyCluster and AnalyticalModel

**Comment by michaldengusiak** [comment]
approved

![image](https://user-images.githubusercontent.com/26113670/87515103-3884fe00-c673-11ea-9433-3b29ae8d0561.png)
