### ISSUE TITLE
add conditions: greater than, less than etc..

### ISSUE THREAD

**Issue by michaldengusiak** [HoareLea/SAM#146]
**Describe the solution you'd like**

to allow filter elements by value
**Additional context**

https://github.com/HoareLea/SAM/issues/134

**Comment by ZiolkowskiJakub** [comment]
Implemented:

![image](https://user-images.githubusercontent.com/16777757/87663059-22526d00-c75b-11ea-99cc-04eae48a8409.png)

**Comment by michaldengusiak** [comment]
done and implemented

![image](https://user-images.githubusercontent.com/26113670/87762471-19b96f80-c80b-11ea-9697-228874c20d2b.png)
