### ISSUE TITLE
Face3D: Rename GetEdges, GetInternalEdges and GetExternalEdge

### ISSUE THREAD

**Issue by ZiolkowskiJakub** [HoareLea/SAM#148]
**Describe the solution you'd like**
Names have to be changed to allow integration with SAM workflow.

GetEdges rename to GetEdges3D
GetInternalEdges rename to GetInternalEdge3Ds
GetExternalEdge rename to GetExternalEdge3D

**Comment by ZiolkowskiJakub** [comment]
Hi @willhl,

I am currently updating Face Face2D and Face3D definitions what will influence the structure of JSON.

Face3D class have two properties InternalEdges and ExternalEdge which will be renamed to:
InternalEdges => InternalEdge2Ds
ExternalEdge => ExternalEdge2D

I hope this not influence too much of your integration. Please let me know if you have any question

**Comment by ZiolkowskiJakub** [comment]
Hi @michaldengusiak,

This change will influence Inspect Component in Grasshopper. Please look for:
InternalEdge3Ds instead InternalEdges
ExternalEdge3D instead ExternalEdge

Two new properties shall appear after this change:
InternalEdge2Ds
ExternalEdge2D

We should have access to 2D and 3D geometry after this change.

**Comment by michaldengusiak** [comment]
done and implemented
![image](https://user-images.githubusercontent.com/26113670/87761673-c7c41a00-c809-11ea-8cca-78a4fa059f2a.png)
