### ISSUE TITLE
Bug in SAMAnalytical.CreatePanel

### ISSUE THREAD

**Issue by michalinadengusiak** [HoareLea/SAM#15]
Hi I just wanted to try out SAM for the first time because of the finally beautiful new icons.

Yet when I was trying to take a polygon into SAM for the first time an error occurred saying that the input is invalid. I think I didn't make a mistake but I haven't used Sam before...

My grasshopper script:
![image](https://user-images.githubusercontent.com/37042279/73009131-d8ba4280-3e07-11ea-90cb-a28608183802.png)

This is my geometry:
![image](https://user-images.githubusercontent.com/37042279/73011417-1620cf00-3e0c-11ea-8e48-6d848fde8f1b.png)

This is my zip file:
[SAM_createPanel_bug.zip](https://github.com/HoareLea/SAM/files/4104751/SAM_createPanel_bug.zip)

**Comment by michaldengusiak** [comment]
@michalinadengusiak 
Thanks for your time testing this. I did explore this issue and realized that our Panel stop working for Polyline and is supporting just a Surface

this will be fixes next week 
![image](https://user-images.githubusercontent.com/26113670/73062473-5f1c6600-3e94-11ea-9346-b233594c6322.png)

**Comment by michaldengusiak** [comment]
@michalinadengusiak 
It is fixed and is now working on all types, 
![image](https://user-images.githubusercontent.com/26113670/73263636-e5081c00-41c8-11ea-8b9f-d502130b75f1.png)
