### ISSUE TITLE
add Space LevelName

### ISSUE THREAD

**Issue by michaldengusiak** [HoareLea/SAM#187]
**Describe the solution you'd like**

add source Level Name if exisit ie. Revit

`aZone.description = string.Format("[Id]={0}; [LevelName]={1}", agbXMLSpace.CADObjectId, agbXMLBuildingStoreyList.Find(x => x.Id == agbXMLSpace.BuidingStoreyId).Name);`

**Additional context**

**Comment by ZiolkowskiJakub** [comment]
Update [Id] to [Element Id]
Update [LevelName] to [Level Name]

**Comment by michaldengusiak** [comment]
added
![image](https://user-images.githubusercontent.com/26113670/113829852-e4302a00-977d-11eb-8797-b0850f2d0626.png)
