### ISSUE TITLE
SetApertureType

### ISSUE THREAD

**Issue by michaldengusiak** [HoareLea/SAM#267]
**Describe the solution you'd like**

as input
1. _Panel, AdjCluter, Analytcial Model
2. Aperture_
3. ApertureType_
**Additional context**

currently we use like that
![image](https://user-images.githubusercontent.com/26113670/131116097-afe1e234-a88d-4819-a879-9d99ae29a53c.png)

**Comment by ZiolkowskiJakub** [comment]
You cannot Change ApertureType without updating ApertureConstruction. I suggest to use following combination:

![image](https://user-images.githubusercontent.com/16777757/132019596-12ad9c61-de64-47df-b3bb-371602d6cc1e.png)

**Comment by michaldengusiak** [comment]
ok
