### ISSUE TITLE
Add AnalyticalCreatePanel

### ISSUE THREAD

**Issue by michaldengusiak** [HoareLea/SAM#3]
- [x] Dynamo

AnalyticalCreatePanel add default name
`SIM_EXT_SLD Default`

**Comment by ZiolkowskiJakub** [comment]
Done

**Comment by michaldengusiak** [comment]
tested and approved
![image](https://user-images.githubusercontent.com/26113670/75790214-c31f2d80-5d62-11ea-97bf-2ed257c2f133.png)
