### ISSUE TITLE
No underscore at SAMAnalytical.CreatePanel at construction

### ISSUE THREAD

**Issue by michalinadengusiak** [HoareLea/SAM#42]
No underscore at SAMAnalytical.CreatePanel at construction.
![image](https://user-images.githubusercontent.com/37042279/77227005-d9a7f000-6b7c-11ea-8da9-fe403a0f1ba9.png)

**Comment by michaldengusiak** [comment]
fixed, tested and approved
![image](https://user-images.githubusercontent.com/26113670/77343713-0fd6a280-6d2a-11ea-93e3-f7745536c593.png)
