### ISSUE TITLE
A missing underscore at SAMAnalytical.AddAperture in apertureConstruction

### ISSUE THREAD

**Issue by michalinadengusiak** [HoareLea/SAM#43]
A missing underscore at SAMAnalytical.AddAperture in apertureConstruction.

![image](https://user-images.githubusercontent.com/37042279/77227019-0e1bac00-6b7d-11ea-9c24-7a5fb5258c1a.png)

**Comment by michaldengusiak** [comment]
fixed and approved

![image](https://user-images.githubusercontent.com/26113670/77344506-292c1e80-6d2b-11ea-8fc0-6f9613fe8542.png)
