### ISSUE TITLE
Wrong underscore at spaces in SAMAnalytical.CreateAdjacencyCluster

### ISSUE THREAD

**Issue by michalinadengusiak** [HoareLea/SAM#44]
Wrong underscore at spaces in SAMAnalytical.CreateAdjacencyCluster.
![image](https://user-images.githubusercontent.com/37042279/77227256-47551b80-6b7f-11ea-9233-accdf6a1a94e.png)

**Comment by michaldengusiak** [comment]
thanks fixed
![image](https://user-images.githubusercontent.com/26113670/77343437-92ab2d80-6d29-11ea-87f7-35136ddfa6f6.png)
