### ISSUE TITLE
The SAMAdjacency. CreateAdjacencyCluster turns floor into roof

### ISSUE THREAD

**Issue by michalinadengusiak** [HoareLea/SAM#45]
Somehow in the SAMAnalytical.CreateAdjacencyCluster the floor turns into a roof. This is a very big issue yet in the SAMAdjacencyCluster.AdjacencyInformation it is correct again. Please fix it, since it can have a big impact on the result. 

![image](https://user-images.githubusercontent.com/37042279/77251157-17744980-6c4d-11ea-8058-7e543ffbf869.png)

This is my zip file:
[SAM_Introduction.zip](https://github.com/HoareLea/SAM/files/4366240/SAM_Introduction.zip)

**Comment by michaldengusiak** [comment]
fix provided
![image](https://user-images.githubusercontent.com/26113670/77305882-b1d89980-6cee-11ea-93bd-4c1e6a121dc4.png)
also solution for manual types assignment
![image](https://user-images.githubusercontent.com/26113670/77305917-bdc45b80-6cee-11ea-8d4a-2c68a0b3861f.png)
