### ISSUE TITLE
Add SetAnalyticalPanelType

### ISSUE THREAD

**Issue by michaldengusiak** [HoareLea/SAM#7]
Allow recognition based on the orientation to PanelType

Floor, Roof, Wall - internal, external
to get more detail recognition we need Topologic recognition of adj spaces
so we need to have 2 level recognition + additional manual

**Comment by ZiolkowskiJakub** [comment]
Done

**Comment by michaldengusiak** [comment]
added, tested and approved
this is now added and control from Create.Panel

so if you do not provide data we will recognize Panel.Type

![image](https://user-images.githubusercontent.com/26113670/76077073-eed72900-5f97-11ea-9e74-f9e6b58fc28b.png)
